---
format: gfm
---

# Overview

*weathergenr* is an R package for generating synthetic weather series using a multivariate, gridded, stochastic weather generator. It builds on the methodology introduced by [Steinscheineder et al (2013)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/wrcr.20528), and provides an efficient, user-friendly implementation tailored for climate and hydrological studies.

Key features include:

:open_file_folder: Support for gridded NetCDF datasets  
:gear: Script automation and enhanced usability  
:zap: Significant performance gains via vectorized and parallelized code

# Installation

Before installing, make sure you have:

- [R](https://cran.r-project.org/bin/) installed  
- An R IDE such as [RStudio](https://posit.co/download/rstudio-desktop/)

To install the development version of `weathergenr` from GitHub:

```{r, eval = FALSE}
#install.packages("devtools")
#devtools::install_github("Deltares/weathergenr")
```

# Quick start

Work-in-progress tutorials and examples are available below:

<br />
[:blue_book: Getting Started vignette](https://github.com/Deltares-research/weathergenr/blob/Dev/Vignettes/getting_started.md)
<br />

Stay tuned - more vignettes and usage examples will be added as the package evolves.

# Licence

Copyright (c) 2019, Deltares

Licensed under the MIT License.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
