obs_data         = ncdata$data
obs_grid         = ncdata$grid
obs_dates        = ncdata$date
vars             = config$vars
n_years          = config$n_years
start_year       = config$start_year
year_start_month = config$year_start_month
n_realizations   = config$n_realizations
warm_var         = config$warm_var
warm_signif      = config$warm_signif
warm_pool_size   = config$warm_pool_size
warm_filter_bounds = config$warm_filter_bounds
annual_knn_n     = config$annual_knn_n
wet_q            = config$wet_q
extreme_q        = config$extreme_q
dry_spell_factor = config$dry_spell_factor
wet_spell_factor = config$wet_spell_factor
out_dir          = out_dir
parallel         = config$parallel
n_cores          = config$n_cores
seed             = config$seed
verbose          = config$verbose
save_plots       = config$save_plots

relax_priority = c("wavelet", "sd", "tail_low", "tail_high", "mean")
