---
title: "Tutorial1"
output: 
  html_document:
    number_sections: TRUE
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 3
    theme: flatly
    highlight: kate
    css: style.css
vignette: >
  %\VignetteIndexEntry{Tutorial1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", message=FALSE, eval = FALSE)
```

The goal of this document is to get you up and running with gridwegen as quickly as possible. 

# Basic functionality

For illustration, we will be using the gridded data for Ntoum basin in ....
  
```{r package}
# Install the latest version from github
devtools::install_github("tanerumit/gridwegen")

# Load package and dependencies
library(gridwegen)
```



## Read-in netcdf files
```{r climdata}

# specify sample netcdf file from the gridwegen package
nc_file <- system.file("extdata", "ntoum_era5_data.nc", package = "gridwegen")

# Read-in gridded weather data from netcdf
nc_data <- readNetcdf(nc_file) 
```


Define climate parameters

```{r parameters}
# Climate change perturbations
precip_changes <- list()
precip_changes$increments <- 2
precip_changes$mean <- list()
precip_changes$var  <- list()

temp_changes <- list()
temp_changes$increments <- 3
temp_changes$mean <- list()

# Monthly precip changes   Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
precip_changes$mean$min <- c(0.7, 0.7, 0.8, 0.8, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7)
precip_changes$mean$max <- c(1.3, 1.3, 1.4, 1.4, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3)
precip_changes$var$min <- c(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
precip_changes$var$max <- c(1.3, 1.3, 1.5, 1.5, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3)

# Monthly temp. changes   Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
temp_changes$mean$min <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
temp_changes$mean$max <- c(3.0, 3.2, 3.4, 4.0, 4.1, 4.4, 5.0, 3.5, 3.3, 2.9, 2.8, 2.7)
```


## Run weather wegenerator

```{r run, echo=TRUE}

# choose which variables to include in the weather generator outputs
variables <- c("precip", "temp", "temp_min", "temp_max")

# Set labels and units for the selected variables
variable_labels = c("Precipitation", "Mean Temperature", "Minimum Temperature", "Maximum Temperature")
variable_units = c("mm/day", "DegC", "DegC", "DegC")

# Set path to store weather generator results 
output_path <- "C:/tesrun"


simulateWeather(
     climate.data = nc_data$data,
     climate.grid = nc_data$coords,
     year.start = 1981,
     year.num = 40,
     month.start = 1,
     variable.names = variables,
     variable.labels = variable_labels,
     variable.units = variable_units,
     sim.year.start = 2020,
     sim.year.num = 40,
     realization.num = 3,
     warm.variable = "precip",
     warm.signif.level = 0.90,
     warm.sample.size = 20000,
     knn.annual.sample.size = 100,
     wet.state.threshold = 0.1,
     extreme.state.quantile = 0.8,
     apply.delta.changes = FALSE,
     evaluate.model = TRUE,
     evaluate.grid.num = 20,
     apply.step.changes = TRUE,
     delta.precip = precip_changes,
     delta.temp = temp_changes,
     output.path = output_path,
     output.ncfile.template = nc_data,
     output.ncfile.prefix = "clim_change_rlz",
     bounds = list(
        mean = c(0.95,1.05),
        sd = c(0.90,1.10),
        min = c(0.90,1.15),
        max = c(0.85,1.10),
        power = c(0.50,2.50),
        nonsignif.threshold = 0.75)
)
```


