---
title: "Simple tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simple tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", message=FALSE)
```

The goal of this document is to get you up and running with gridwegen as quickly as possible. 

## Basic functionality

For illustration, we will be using the gridded data for Ntoum basin in ....

### Reading in netcdf files

```{r climatedata}
library(gridwegen)

nc_file <- "ntoum.nc"
nc_path <- system.file('extdata', package = 'gridwegen')
nc_dimnames <- list(x = "lon", y = "lat", time = "time")
nc_variables <- c("precip", "temp", "temp_min", "temp_max")
origin_date <- as.Date("1981-01-01")

nc_data <- readNetcdf(
    nc.path = nc_path,
    nc.file = nc_file,
    nc.dimnames = nc_dimnames,
    nc.variables = nc_variables,
    origin.date = origin_date,
    has.leap.days = TRUE)

# Climate data and grid information
climate_data = nc_data$data
climate_grid = nc_data$coords
```


### Define essential parameters
```{r parameters}
project_name = "ntoum"
output_path = paste0("C:/wegentest/", project_name, "/")
variable_names = c("precip",  "temp", "temp_min", "temp_max")
variable_labels = c("Precipitation", "Mean Temperature", "Minimum Temperature", "Maximum Temperature")
variable_units = c("mm/day", "DegC", "DegC", "DegC")
warm_variable = "precip"
year_start = 1981
year_num = 40
sim_year_start = 2020
sim_year_num = 40

# Warm model
warm_variable <- "precip"
realization_num = 1
month_start = 5

# Climate changes
############################ Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
precip_changes_mean_min <- c(0.7, 0.7, 0.8, 0.8, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7)
precip_changes_mean_max <- c(1.3, 1.3, 1.4, 1.4, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3)
precip_changes_var_min  <- c(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0)
precip_changes_var_max  <- c(1.3, 1.3, 1.5, 1.5, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3)
precip_changes_increments <- 2

############################ Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
temp_changes_mean_min   <- c(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
temp_changes_mean_max   <- c(3.0, 3.2, 3.4, 4.0, 4.1, 4.4, 5.0, 3.5, 3.3, 2.9, 2.8, 2.7)
temp_changes_increments <- 3

# Climate change perturbations
precip_changes <- list()
precip_changes$increments <- precip_changes_increments
precip_changes$mean <- list()
precip_changes$mean$min <- precip_changes_mean_min
precip_changes$mean$max <- precip_changes_mean_max
precip_changes$var  <- list()
precip_changes$var$min  <-  precip_changes_var_min
precip_changes$var$max  <-  precip_changes_var_max

temp_changes <- list()
temp_changes$increments <- temp_changes_increments
temp_changes$mean <- list()
temp_changes$mean$min <- temp_changes_mean_min
temp_changes$mean$max <- temp_changes_mean_max
```


### Run weather generator
```{r model-run, eval=FALSE, echo=TRUE}
simulateGriddedWeather(
  climate.data = climate_data,
  climate.grid = climate_grid,
  year.start = year_start,
  year.num = year_num,
  output.path = output_path,
  variable.names = variable_names,
  variable.labels = variable_labels,
  variable.units = variable_units,
  warm.variable = warm_variable,
  sim.year.start = sim_year_start,
  sim.year.num = sim_year_num,
  realization.num = realization_num,
  month.start = month_start,
  precip.changes = precip_changes,
  temp.changes = temp_changes,
  warm.signif.level = 0.90,
  warm.sample.size = 5000,
  knn.annual.sample.size = 20,
  save.warm.results = TRUE,
  check.model.performace = TRUE,
  check.model.grid.num = 20,
  impose.climate.change = TRUE,
  output.file.prefix = "clim_change_rlz",
  save.scenario.matrix = TRUE,
  apply.step.changes = TRUE)
```

