
Description: >
  This yml file includes general parameters to configure the weather generator
  and parameters for the generateWeatherSeries function.

general:
  weathergen_output_path: C:/testrun2/
  weathergen_input_ncfile: C:/Users/taner/OneDrive - Stichting Deltares/Documents/R/win-library/4.1/gridwegen/extdata/ntoum_era5_data.nc
  variables:
      - precip
      - temp
      - temp_min
      - temp_max
  historical_realizations_num: 3

generateWeatherSeries:
  sim.year.start: 2020
  month.start: 1
  realization.num: 5
  warm.variable: precip
  warm.signif.level: 0.90
  warm.sample.num: 5000
  knn.sample.num: 100
  mc.wet.threshold: 0.3
  mc.extreme.quantile: 0.8
  evaluate.model: TRUE
  evaluate.grid.num: 20
  seed: 12345
